language: python
sudo: false

os: linux

arch:
 - amd64
 - ppc64le
 
env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"
  
jobs:
  exclude:
      - arch: ppc64le
        env: LUA="luajit=2.0"
      - arch: ppc64le
        env: LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install luasec # optional dependency
  - luarocks install luacov
  - luarocks install luacheck
  - luarocks install luacov-coveralls

script:
  - luarocks make
  - luacheck .
  - make coverage

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install --exclude tests

branches:
  except:
    - gh-pages
